import Head from 'next/head'
import Card from '../components/Card/card'
import CardContainer from '../components/Card/cardContainer'
import NavBar from '../components/Navbar/navBar'



export default function Home() {
  return (
    <>
      <Head>
        <title>Gamerland</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      
      <CardContainer/>
      
     
     

    </>
  )
}
